### PR TITLE
Update for Swift 3 compatibility

### PR DESCRIPTION
**Pull request by regnerjr**
I see reference in the project file to an example project?
Should this be updated too?

Let me know if I can help of clean up anything further. 

Hope this helps.

### CODE REVIEW

**Comment by angelodipaolo** [comment]
Thanks for taking the time to update this for Swift 3! It would be great if you could also update the example project.

Since the Swift 3 changes are breaking API changes and will require a major version bump, I'd like to take this opportunity to improve the API and make other breaking changes. Mainly, [replacing `NetworkStatusInterpreter` with an enum](https://github.com/Electrode-iOS/ELReachability/issues/4). Because of this, I'd like to wait to merge your Swift 3 updates into master until after the API changes are in so I can tag a stable 2.0.0 release. Could you please open a new PR with the new `swift3` branch I just pushed up as the base instead of `master`?

Also, if you have any interest in taking on [#4](https://github.com/Electrode-iOS/ELReachability/issues/4) feel free to make the changes as part of your PR.

**Comment by regnerjr** [comment]
Thanks for the encouragement @angelodipaolo I'll try to get to these changes over the next few days. I'll open an new pr to the new branch, and look at making the updates outlined in #4.

**Comment by angelodipaolo** [comment]
@regnerjr no need to worry about making the changes in #4 now that @nonsensery fixed it with a slightly different in approach.

**Comment by regnerjr** [comment]
Having some trouble getting some of the symbols to export correctly across the swift objc boundary. 
Will try again later when I have some more time. Thanks.

**Pull request closed without merging**
